on:
  push:
    branches:
      - master

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make prerelease to npm
        uses: epeli/npm-release@bc78fc8
        with:
          type: prerelease
          token: ${{ secrets.NPM_TOKEN }}
