on:
  push:
    branches:
      - master

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: prepare default version
        run: npm run prepare:default
      - name: Make prerelease of default version to npm
        uses: epeli/npm-release@bc78fc8caa52fa9541f83b3fbaa2fc9938bdf0ee
        with:
          type: prerelease
          token: ${{ secrets.NPM_TOKEN }}
      - name: prepare core version
        run: |
          npm run reset
          npm run prepare:core
      - name: Make prerelease of core version to npm
        uses: epeli/npm-release@bc78fc8caa52fa9541f83b3fbaa2fc9938bdf0ee
        with:
          type: prerelease
          token: ${{ secrets.NPM_TOKEN }}
